---
# Ansible Inventory for Proxmox LXC Containers
# This inventory runs on the Proxmox host itself
all:
  children:
    proxmox_host:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    
    lxc_containers:
      hosts:
        # Example container without GPU
        example-app:
          lxc_id: 201
          
        # Example container with GPU
        gpu-app:
          lxc_id: 202
