all:
  children:
    proxmox_api:
      hosts:
        proxmox_api_controller:
    lxcs:
      # Add each managed container name under hosts once you create host_vars/<container>.yml.
      hosts: {jellyfin_lxc}
