all:
  children:
    proxmox_api:
      hosts:
        proxmox_api_controller:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
    lxcs:
      # Add each managed container name under hosts once you create host_vars/<container>.yml.
      hosts:
        jellyfin_lxc:
